name: safe
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.1
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - comm=0.2.3
  - debugpy=1.8.18
  - decorator=5.2.1
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - expat=2.7.3
  - ipykernel=7.1.0
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libsodium=1.0.20
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.6.0
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.3
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - psutil=7.2.1
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.1
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.3
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - aenum==3.1.15
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anthropic==0.75.0
      - antlr4-python3-runtime==4.13.2
      - anyio==4.12.1
      - async-timeout==5.0.1
      - asyncio-throttle==1.0.2
      - attrs==25.4.0
      - backports-asyncio-runner==1.2.0
      - black==25.12.0
      - boto3==1.42.26
      - botocore==1.42.26
      - certifi==2026.1.4
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - colorlog==6.10.1
      - dataproperty==1.1.0
      - datasets==4.4.2
      - dill==0.4.0
      - distro==1.9.0
      - docstring-parser==0.17.0
      - extension-helpers==1.4.0
      - filelock==3.20.3
      - flake8==7.3.0
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.29.0
      - google-api-python-client==2.187.0
      - google-auth==2.47.0
      - google-auth-httplib2==0.3.0
      - google-generativeai==0.8.6
      - googleapis-common-protos==1.72.0
      - grpcio==1.76.0
      - grpcio-status==1.71.2
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httpx==0.28.1
      - huggingface-hub==1.3.2
      - hypothesis==6.150.2
      - idna==3.11
      - iniconfig==2.3.0
      - jinja2==3.1.6
      - jiter==0.12.0
      - jmespath==1.0.1
      - joblib==1.5.3
      - jsonlines==4.0.0
      - langcodes==3.5.1
      - latex2sympy2-extended==1.0.6
      - lighteval==0.11.0
      - lizard==1.19.0
      - lxml==6.0.2
      - mando==0.7.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mbstrdecoder==1.1.4
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - mypy-extensions==1.1.0
      - networkx==3.4.2
      - nltk==3.9.1
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - openai==2.15.0
      - pandas==2.3.3
      - pathspec==1.0.3
      - pathvalidate==3.3.1
      - pluggy==1.6.0
      - portalocker==3.2.0
      - propcache==0.4.1
      - proto-plus==1.27.0
      - protobuf==5.29.5
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycodestyle==2.14.0
      - pycountry==24.6.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyerfa==2.0.1.5
      - pyflakes==3.4.0
      - pygame==2.6.1
      - pyparsing==3.3.1
      - pytablewriter==1.2.1
      - pytest==9.0.2
      - pytest-asyncio==1.3.0
      - pytokens==0.3.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - radon==6.0.1
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - rouge-score==0.1.2
      - rsa==4.9.1
      - s3transfer==0.16.0
      - sacrebleu==2.6.0
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentence-transformers==5.2.0
      - sentencepiece==0.2.1
      - setuptools-scm==9.2.2
      - shellingham==1.5.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - sympy==1.14.0
      - tabledata==1.3.4
      - tabulate==0.9.0
      - tcolorpy==0.1.7
      - termcolor==2.3.0
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tokenizers==0.22.2
      - tomli==2.4.0
      - torch==2.9.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - tree-sitter==0.25.2
      - tree-sitter-cpp==0.23.4
      - tree-sitter-go==0.25.0
      - tree-sitter-java==0.23.5
      - tree-sitter-javascript==0.25.0
      - tree-sitter-python==0.25.0
      - tree-sitter-typescript==0.23.2
      - triton==3.5.1
      - typepy==1.3.4
      - typer==0.21.1
      - typer-slim==0.21.1
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uritemplate==4.2.0
      - urllib3==2.6.3
      - xxhash==3.6.0
      - yarl==1.22.0